apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: {{ template "graylog.fullname" . }}-elasticsearch
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      svcmon: elasticsearch-exporter-{{ .Release.Name }}
