{{- $servicePath := include "graylog.slave.fullname" . -}}
{{- $externalDomain := include "graylog.ingress.externalDomain" . -}}
{{- $externalProtocol := include "graylog.ingress.externalProtocol" . -}}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "graylog.slave.fullname" . }}
  labels:
    app: {{ template "graylog.name" . }}-slave
    chart: {{ template "graylog.chart" . }}
    component: graylog-slave
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "graylog.slave.fullname" . }}
  replicas: {{ .Values.graylog.slave.replicaCount }}
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        graylog: "true"
        app: {{ template "graylog.name" . }}
        component: graylog-slave
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 70
      initContainers:
        - name: init-mongodb-replicaset
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-mongodb-replicaset; do echo waiting for {{ .Release.Name }}-mongodb-replicaset; sleep 2; done;']
        - name: init-elasticsearch-client
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-elasticsearch-client; do echo waiting for {{ .Release.Name }}-elasticsearch-client; sleep 2; done;']
      containers:
        - name: graylog-slave
          image: "{{ .Values.graylog.image.repository }}:{{ .Values.graylog.image.tag }}"
          imagePullPolicy: Always
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: GRAYLOG_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "graylog.master.fullname" . }}
                key: password-secret
          - name: GRAYLOG_ROOT_PASSWORD_SHA2
            valueFrom:
              secretKeyRef:
                name: {{ template "graylog.master.fullname" . }}
                key: root-password-sha256
          - name: GRAYLOG_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "graylog.master.fullname" . }}
                key: root-username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mongodb.fullname" . }}-auth
                key: password
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "mongodb.fullname" . }}-auth
                key: username
          - name: GRAYLOG_MONGODB_URI
            value: "mongodb://$MONGODB_ROOT_USERNAME:$MONGODB_ROOT_PASSWORD@{{ template "mongodb.fullname" . }}-gvr:27017/{{ .Values.mongodb.mongodbDatabase }}?replicaSet={{ .Values.mongodb.replicaSetName }}"
          - name: GRAYLOG_IS_MASTER
            value: "false"
          - name: GRAYLOG_ELASTICSEARCH_HOSTS
            value: "http://{{ .Release.Name }}-elasticsearch-client:9200"
          - name: GRAYLOG_WEB_LISTEN_URI
            value: "http://0.0.0.0:{{ .Values.graylog.web.service.internalPort }}/"
          - name: GRAYLOG_WEB_ENDPOINT_URI
            value: "{{ $externalProtocol }}://{{ .Release.Name }}.{{ $externalDomain }}/api"
          - name: GRAYLOG_REST_LISTEN_URI
            value: "http://0.0.0.0:{{ .Values.graylog.web.service.internalPort }}/api/"
          - name: GRAYLOG_REST_TRANSPORT_URI
            value: "http://$(MY_POD_IP):{{ .Values.graylog.web.service.internalPort }}/api/"
          ports:
          - containerPort: {{ .Values.graylog.web.service.internalPort }}
            name: http
          - containerPort: 12201
            name: gelf-input
          - containerPort: 1514
            name: syslog-input
          volumeMounts:
          - name: graylog-persistent-storage
            mountPath: /usr/share/graylog/data/journal
            subPath: graylog
          resources:
{{ toYaml .Values.graylog.slave.containers.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /api/system/lbstatus
              port: {{ .Values.graylog.web.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 4
    {{- with .Values.graylog.slave.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: graylog-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "{{ .Values.graylog.storageClass }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{ .Values.graylog.storageSize }}"
