apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "graylog.slave.fullname" . }}
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "graylog.slave.fullname" . }}
  targetCPUUtilizationPercentage: 80