apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
      app: {{ template "graylog.name" . }}
      chart: {{ template "graylog.chart" . }}
      component: graylog-master
      heritage: {{ .Release.Service }}
      prometheus: kube-prometheus
  resources:
    requests:
      memory: 400Mi