apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graylog.server.fullname" . }}
  labels:
    app: {{ template "graylog.server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"  
type: Opaque
data:
  {{ if .Values.graylog.passwordSecret }}
  password-secret:  {{ .Values.graylog.passwordSecret | b64enc | quote }}
  {{ else }}
  password-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.graylog.rootPassword }}
  root-password:  {{ .Values.graylog.rootPassword | b64enc | quote }}
  root-password-sha256:  {{ .Values.graylog.rootPassword | sha256sum | b64enc | quote }}
  {{ else }}
  {{ $randpassword := randAlphaNum 10 }}
  root-password: {{ $randpassword | b64enc | quote }}
  root-password-sha256:  {{ $randpassword | sha256sum | b64enc | quote }}
  {{ end }}
  {{ if .Values.graylog.rootUsername }}  
  root-username:  {{ .Values.graylog.rootUsername | b64enc | quote }}
  {{ else }}
  root-username: {{ "admin" | b64enc | quote }}
  {{ end }}