apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graylog.master.fullname" . }}
  labels:
    app: {{ template "graylog.master.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"  
type: Opaque
data:
  {{ if .Values.graylog.passwordSecret }}
  password-secret:  {{ .Values.graylog.passwordSecret | b64enc | quote }}
  {{ else }}
  password-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.graylog.passwordSecret }}
  admin-password:  {{ .Values.graylog.adminPassword | b64enc | quote }}
  admin-password-sha256:  {{ .Values.graylog.adminPassword | sha256 | b64enc | quote }}
  {{ else }}
  {{ $randpassword := randAlphaNum 10 }}
  admin-password: {{ $randpassword | b64enc | quote }}
  admin-password-sha256:  {{ $randpassword | sha256sum | b64enc | quote }}
  {{ end }}
  admin-user: {{ "admin" | b64enc | quote }}
