dependencies:
  - name: mongodb-replicaset
    version: 3.4.0
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  - name: elasticsearch
    version: 1.13.3
    repository: "https://kubernetes-charts.storage.googleapis.com/"