
ingress:
  name: graylog
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  protocol: https
  domain: local

mongodb:
  version: 3.6-v1
  replicas: 3
  replicaSetName: koen
  storage:
    storageClass: gp2
    storageSize: 5Gi
  mongodbDatabase: graylog

elasticsearch:
  version: 6.4
  client:
    storage:
      storageClass: gp2
      storageSize: 1Gi
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 256m
      memory: 512Mi
    replicas: 2
  master:
    storage:
      storageClass: gp2
      storageSize: 4Gi
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 256m
      memory: 512Mi
    replicas: 3
  data:
    storage:
      storageClass: gp2
      storageSize: 50Gi
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 1
      memory: 1536Mi
    replicas: 3

graylog:
  name: graylog
  appVersion: 2.4.6

  metrics:
    serviceMonitor:
      additionalLabels:
        release: prometheus

  image:
    repository: "arvatoaws/graylog"
    tag: "latest"

#  rootUsername: admin
#  rootPassword:
#  passwordSecret:

  storageClass: "gp2"
  storageSize: "10Gi"

  web:
    service:
      externalPort: 80
      internalPort: 9000

  master:
    name: master
    replicaCount: 1

    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - graylog-slave
            topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: 1
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi

  slave:
    name: slave
    replicaCount: 2

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - graylog-master
          topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: 1
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi
