

ingress:
  name: ingress
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Should be unneccessary with properly tagged subnets: alb.ingress.kubernetes.io/subnets: subnet-010f41fc189d889dc,subnet-063092fee4e15bca8,subnet-0d271b6dc2e024b3d
    alb.ingress.kubernetes.io/tags: Environment=demo # TODO: Just an example
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:001579709704:certificate/baf3150c-946b-4902-9023-673f953be075
    # TODO: something doesn't work here: alb.ingress.kubernetes.io/load-balancer-attributes:routing.http2.enabled: true
    # TODO: logging bucket: alb.ingress.kubernetes.io/load-balancer-attributes:access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    kubernetes.io/ingress.class: alb
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # path: /
  protocol: http
  domain:
#  proxyDomain:
  externalProtocol: https
  proxyProtocol: https
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


mongodbReplicaset:
  name: mongodb-replicaset


elasticsearch:
  name: elasticsearch
  
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "5.6.4"

  cluster:
    xpackEnable: false
    env:
      xpack.security.enabled: 'false'
      XPACK_MONITORING_ENABLED: 'false'

  master:
    persistence:
      size: "4Gi"
      storageClass: "gp2"

  data:
    persistence:
      size: "500Gi"
      storageClass: "st1"

graylog:
  passwordSecret:
  
  storageClass: "gp2"

  web:
    service:
      externalPort: 80
      internalPort: 9000

  image:
    tag: 2.4.6-1

  master:
    name: master
    replicaCount: 1

    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - graylog-slave
            topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: .25
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi

  slave:
    name: slave
    replicaCount: 2

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - graylog-master
          topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: .25
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi